services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: libgen
      MYSQL_USER: mysql
      MYSQL_PASSWORD: rgb098
    ports:
      - "3306:3306"
    volumes:
      -  /home/DATA/openAlexData/libgen:/var/lib/mysql
  tika:
    image: tika:djvu
    container_name: tika
    ports:
      - "9998:9998"
    environment:
      JaVA_OPTS: "-Xms1g -Xmx2g"  
    restart: unless-stopped
volumes:
  mysql_data: